INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (1, 'John Doe', '2023-07-07', 'head manager', 3, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (2, 'Jane Doe', '2022-06-23', 'cashier', 1, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (3, 'Alice Smith', '2024-08-11', 'cashier', 1, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (4, 'Bob Smith', '2023-11-18', 'manager', 3, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (5, 'Charlie Brown', '2023-07-23', 'manager', 3, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (6, 'Lucy Brown', '2023-05-20', 'cashier', 1, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (7, 'Snoopy Dog', '2024-04-26', 'cashier', 2, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (8, 'Linus Van Pelt', '2023-09-28', 'cashier', 1, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (9, 'Peppermint Patty', '2022-11-30', 'cashier', 2, 1);
INSERT INTO employee (id, name, start_day, job_position, access_level, manager_id) VALUES (10, 'Marcie Johnson', '2023-03-11', 'cashier', 2, 1);
UPDATE employee SET manager_id = 1 WHERE id = 1;
UPDATE employee SET manager_id = 4 WHERE id = 2;
UPDATE employee SET manager_id = 1 WHERE id = 3;
UPDATE employee SET manager_id = 4 WHERE id = 4;
UPDATE employee SET manager_id = 5 WHERE id = 5;
UPDATE employee SET manager_id = 5 WHERE id = 6;
UPDATE employee SET manager_id = 1 WHERE id = 7;
UPDATE employee SET manager_id = 1 WHERE id = 8;
UPDATE employee SET manager_id = 1 WHERE id = 9;
UPDATE employee SET manager_id = 1 WHERE id = 10;