INSERT INTO item (id, name, add_price) 
    VALUES 
        (1, 'Orange Chicken', 0),
        (2, 'Honey Walnut Shrimp', 1.5),
        (3, 'Black Pepper Sirloin Steak', 1.5),
        (4, 'Broccoli Beef', 0),
        (5, 'Kung Pao Chicken', 0),
        (6, 'Honey Sesame Chicken Breast', 0),
        (7, 'Beijing Beef', 0),
        (8, 'String Bean Chicken Breast', 0),
        (9, 'Mushroom Chicken', 0),
        (10,'Grilled Teriyaki', 0),
        (11,'Black Pepper Chicken', 0),
        (12,'SweetFire Chicken Breast', 0),
        (13,'Chow Mein', 0),
        (14,'Fried Rice', 0),
        (15,'Super Greens', 0),
        (16,'White Steamed Rice', 0),
        (17,'Chicken Egg Roll', 0),
        (18,'Veggie Spring Rolls', 0),
        (19,'Cream Cheese Rangoons', 0),
        (20,'Apple Pie Roll', 0);
